//! # Zig-BLE Wireshark PCAP Exporter & Packet Logger
//!
//! Provides zero-allocation streaming of HCI and ATT packets directly into
//! standard libpcap (.pcap) format with Link-Layer DLT_BLUETOOTH_HCI_H4 (187).
//! Files generated by this module can be opened directly in Wireshark for
//! real-time protocol inspection, reverse engineering, and troubleshooting.

const std = @import("std");
const builtin = @import("builtin");

pub const MAGIC_MICROSECONDS: u32 = 0xA1B2C3D4;
pub const MAGIC_NANOSECONDS: u32 = 0xA1B23C4D;
pub const VERSION_MAJOR: u16 = 2;
pub const VERSION_MINOR: u16 = 4;
pub const LINKTYPE_BLUETOOTH_HCI_H4: u32 = 187;

const winapi_cc: std.builtin.CallingConvention = if (builtin.os.tag == .windows) .winapi else .c;

/// Returns current wall-clock seconds and microseconds (Unix epoch).
pub fn getMicroTimestamp() struct { sec: u32, usec: u32 } {
    if (builtin.os.tag == .windows) {
        const K32 = struct {
            extern "kernel32" fn GetSystemTimeAsFileTime(lpSystemTimeAsFileTime: *std.os.windows.FILETIME) callconv(winapi_cc) void;
        };
        var ft: std.os.windows.FILETIME = undefined;
        K32.GetSystemTimeAsFileTime(&ft);
        const intervals: u64 = (@as(u64, ft.dwHighDateTime) << 32) | ft.dwLowDateTime;
        const unix_100ns = if (intervals > 116444736000000000) intervals - 116444736000000000 else 0;
        const total_us = unix_100ns / 10;
        const sec: u32 = @truncate(total_us / 1_000_000);
        const usec: u32 = @truncate(total_us % 1_000_000);
        return .{ .sec = sec, .usec = usec };
    } else if (builtin.os.tag == .linux) {
        var ts: std.os.linux.timespec = undefined;
        _ = std.os.linux.clock_gettime(std.os.linux.CLOCK.REALTIME, &ts);
        const s: u32 = @truncate(@as(u64, @intCast(@max(0, ts.sec))));
        const us: u32 = @truncate(@as(u64, @intCast(@max(0, @divTrunc(ts.nsec, 1000)))));
        return .{ .sec = s, .usec = us };
    } else {
        return .{ .sec = 0, .usec = 0 };
    }
}

/// HCI UART H4 packet indicator prefix
pub const H4PacketType = enum(u8) {
    command = 0x01,
    acl_data = 0x02,
    sco_data = 0x03,
    event = 0x04,
    iso_data = 0x05,
};

/// PCAP Global Header (24 bytes)
pub const PcapGlobalHeader = extern struct {
    magic_number: u32 = MAGIC_MICROSECONDS,
    version_major: u16 = VERSION_MAJOR,
    version_minor: u16 = VERSION_MINOR,
    thiszone: i32 = 0,
    sigfigs: u32 = 0,
    snaplen: u32 = 65535,
    network: u32 = LINKTYPE_BLUETOOTH_HCI_H4,
};

/// PCAP Packet Record Header (16 bytes)
pub const PcapPacketHeader = extern struct {
    ts_sec: u32,
    ts_usec: u32,
    incl_len: u32,
    orig_len: u32,
};

/// In-Memory Buffer Writer (zero-allocation)
pub const BufferWriter = struct {
    buffer: []u8,
    pos: usize = 0,

    pub fn init(buf: []u8) BufferWriter {
        return .{ .buffer = buf, .pos = 0 };
    }

    pub fn writeAll(self: *BufferWriter, bytes: []const u8) error{NoSpaceLeft}!void {
        if (self.pos + bytes.len > self.buffer.len) return error.NoSpaceLeft;
        @memcpy(self.buffer[self.pos .. self.pos + bytes.len], bytes);
        self.pos += bytes.len;
    }

    pub fn getWritten(self: *const BufferWriter) []const u8 {
        return self.buffer[0..self.pos];
    }

    pub fn reset(self: *BufferWriter) void {
        self.pos = 0;
    }
};

/// Generic PCAP Stream Writer
pub fn PcapWriter(comptime WriterType: type) type {
    return struct {
        writer: WriterType,
        header_written: bool = false,

        const Self = @This();

        pub fn init(writer: WriterType) Self {
            return .{
                .writer = writer,
                .header_written = false,
            };
        }

        /// Writes the standard 24-byte PCAP global header.
        pub fn writeHeader(self: *Self) !void {
            if (self.header_written) return;
            const hdr = PcapGlobalHeader{};
            try self.writer.writeAll(std.mem.asBytes(&hdr));
            self.header_written = true;
        }

        /// Writes a raw HCI H4 packet with an explicit timestamp.
        pub fn writePacketWithTimestamp(
            self: *Self,
            pkt_type: H4PacketType,
            data: []const u8,
            sec: u32,
            usec: u32,
        ) !void {
            if (!self.header_written) {
                try self.writeHeader();
            }

            const total_len: u32 = @intCast(1 + data.len);
            const pkt_hdr = PcapPacketHeader{
                .ts_sec = sec,
                .ts_usec = usec,
                .incl_len = total_len,
                .orig_len = total_len,
            };

            try self.writer.writeAll(std.mem.asBytes(&pkt_hdr));
            const type_byte = [_]u8{@intFromEnum(pkt_type)};
            try self.writer.writeAll(&type_byte);
            try self.writer.writeAll(data);
        }

        /// Writes an HCI H4 packet using the current system wall-clock time.
        pub fn writePacket(self: *Self, pkt_type: H4PacketType, data: []const u8) !void {
            const ts = getMicroTimestamp();
            return self.writePacketWithTimestamp(pkt_type, data, ts.sec, ts.usec);
        }

        /// Helper: Writes an HCI Command packet (Host -> Controller).
        pub fn writeHciCommand(self: *Self, raw_cmd_packet: []const u8) !void {
            return self.writePacket(.command, raw_cmd_packet);
        }

        /// Helper: Writes an HCI Event packet (Controller -> Host).
        pub fn writeHciEvent(self: *Self, raw_event_packet: []const u8) !void {
            return self.writePacket(.event, raw_event_packet);
        }

        /// Helper: Writes an HCI ACL Data packet.
        pub fn writeAclData(self: *Self, raw_acl_packet: []const u8) !void {
            return self.writePacket(.acl_data, raw_acl_packet);
        }

        /// Helper: Encapsulates an ATT PDU into an L2CAP B-frame and HCI ACL packet
        /// so Wireshark can decode the full protocol tree (HCI -> L2CAP -> ATT -> GATT).
        pub fn writeAttPdu(
            self: *Self,
            conn_handle: u16,
            cid: u16,
            att_data: []const u8,
        ) !void {
            // HCI ACL Header: [Handle (12-bit) | PB (2-bit) | BC (2-bit)] (2 bytes) + [Total Length] (2 bytes)
            // L2CAP Header:   [Length] (2 bytes) + [CID] (2 bytes)
            var packet_buf: [1024]u8 = undefined;
            const l2cap_len: u16 = @intCast(att_data.len);
            const acl_data_len: u16 = l2cap_len + 4; // L2CAP header is 4 bytes

            if (4 + acl_data_len > packet_buf.len) return error.BufferTooSmall;

            // 1. HCI ACL Header
            // PB = 00 (First non-automatically-flushable packet)
            const handle_and_flags = conn_handle & 0x0FFF;
            packet_buf[0] = @intCast(handle_and_flags & 0xFF);
            packet_buf[1] = @intCast((handle_and_flags >> 8) & 0xFF);
            packet_buf[2] = @intCast(acl_data_len & 0xFF);
            packet_buf[3] = @intCast((acl_data_len >> 8) & 0xFF);

            // 2. L2CAP B-Frame Header
            packet_buf[4] = @intCast(l2cap_len & 0xFF);
            packet_buf[5] = @intCast((l2cap_len >> 8) & 0xFF);
            packet_buf[6] = @intCast(cid & 0xFF);
            packet_buf[7] = @intCast((cid >> 8) & 0xFF);

            // 3. ATT PDU Payload
            @memcpy(packet_buf[8 .. 8 + att_data.len], att_data);

            const total_acl_packet = packet_buf[0 .. 4 + acl_data_len];
            return self.writePacket(.acl_data, total_acl_packet);
        }
    };
}

test "PcapWriter global header and packet framing test" {
    var buffer: [512]u8 = undefined;
    var writer = BufferWriter.init(&buffer);

    var pcap = PcapWriter(*BufferWriter).init(&writer);
    try pcap.writeHeader();

    // Verify 24-byte global header
    const written_hdr = buffer[0..24];
    const magic = std.mem.readInt(u32, written_hdr[0..4], .little);
    try std.testing.expectEqual(MAGIC_MICROSECONDS, magic);
    const ver_major = std.mem.readInt(u16, written_hdr[4..6], .little);
    try std.testing.expectEqual(@as(u16, 2), ver_major);
    const link_type = std.mem.readInt(u32, written_hdr[20..24], .little);
    try std.testing.expectEqual(LINKTYPE_BLUETOOTH_HCI_H4, link_type);

    // Write a mock HCI Command (Reset: OGF 0x03, OCF 0x0003 -> Opcode 0x0C03, param len 0)
    const hci_reset = [_]u8{ 0x03, 0x0C, 0x00 };
    try pcap.writePacketWithTimestamp(.command, &hci_reset, 100, 500);

    // Verify 16-byte packet header + 1-byte H4 type + 3-byte payload = 20 bytes
    const pkt_offset = 24;
    const pkt_hdr = buffer[pkt_offset .. pkt_offset + 16];
    const ts_sec = std.mem.readInt(u32, pkt_hdr[0..4], .little);
    try std.testing.expectEqual(@as(u32, 100), ts_sec);
    const ts_usec = std.mem.readInt(u32, pkt_hdr[4..8], .little);
    try std.testing.expectEqual(@as(u32, 500), ts_usec);
    const incl_len = std.mem.readInt(u32, pkt_hdr[8..12], .little);
    try std.testing.expectEqual(@as(u32, 4), incl_len); // 1 byte H4 + 3 bytes payload

    // H4 Indicator
    try std.testing.expectEqual(@as(u8, 0x01), buffer[pkt_offset + 16]);
    // Payload
    try std.testing.expectEqualSlices(u8, &hci_reset, buffer[pkt_offset + 17 .. pkt_offset + 20]);
}

test "PcapWriter writeAttPdu encapsulating into L2CAP and HCI ACL" {
    var buffer: [512]u8 = undefined;
    var writer = BufferWriter.init(&buffer);

    var pcap = PcapWriter(*BufferWriter).init(&writer);

    // Write an ATT Exchange MTU Request: Opcode 0x02, Client MTU 517 (0x0205)
    const att_exchange_mtu = [_]u8{ 0x02, 0x05, 0x02 };
    try pcap.writeAttPdu(0x0040, 0x0004, &att_exchange_mtu);

    // Total size: 24 (global header) + 16 (pkt header) + 1 (H4 ACL) + 4 (HCI ACL) + 4 (L2CAP) + 3 (ATT) = 52 bytes
    const total_written = writer.getWritten().len;
    try std.testing.expectEqual(@as(usize, 52), total_written);

    // H4 Type should be ACL Data (0x02)
    try std.testing.expectEqual(@as(u8, 0x02), buffer[40]);

    // L2CAP CID at offset 40 + 1 (H4) + 4 (ACL) + 2 (L2CAP len) = 47
    const cid = std.mem.readInt(u16, buffer[47..49], .little);
    try std.testing.expectEqual(@as(u16, 0x0004), cid); // ATT CID

    // ATT Opcode at offset 49
    try std.testing.expectEqual(@as(u8, 0x02), buffer[49]);
}

// ============================================================================
// Capture Readers: PCAP & Android Btsnoop (RFC 1761)
// ============================================================================

/// Parsed PCAP packet borrowing directly from the capture buffer.
pub const PcapPacket = struct {
    sec: u32,
    usec: u32,
    orig_len: u32,
    data: []const u8,
};

/// Zero-allocation, streaming reader for standard .pcap captures.
pub const PcapReader = struct {
    bytes: []const u8,
    cursor: usize = 0,
    endian: std.builtin.Endian = .little,
    nanoseconds: bool = false,
    link_type: u32 = 0,

    pub fn init(bytes: []const u8) !PcapReader {
        if (bytes.len < 24) return error.PayloadTooShort;

        const magic_le = std.mem.readInt(u32, bytes[0..4], .little);
        var endian: std.builtin.Endian = .little;
        var nano = false;

        if (magic_le == MAGIC_MICROSECONDS) {
            endian = .little;
            nano = false;
        } else if (magic_le == MAGIC_NANOSECONDS) {
            endian = .little;
            nano = true;
        } else if (magic_le == 0xD4C3B2A1) {
            endian = .big;
            nano = false;
        } else if (magic_le == 0x4D3CB2A1) {
            endian = .big;
            nano = true;
        } else {
            return error.InvalidPcapMagic;
        }

        const link = std.mem.readInt(u32, bytes[20..24], endian);

        return .{
            .bytes = bytes,
            .cursor = 24,
            .endian = endian,
            .nanoseconds = nano,
            .link_type = link,
        };
    }

    /// Reads the next packet record. Returns `null` at EOF.
    pub fn next(self: *PcapReader) !?PcapPacket {
        if (self.cursor >= self.bytes.len) return null;
        if (self.bytes.len - self.cursor < 16) return error.UnexpectedEof;

        const hdr = self.bytes[self.cursor .. self.cursor + 16];
        const sec = std.mem.readInt(u32, hdr[0..4], self.endian);
        const usec = std.mem.readInt(u32, hdr[4..8], self.endian);
        const incl_len = std.mem.readInt(u32, hdr[8..12], self.endian);
        const orig_len = std.mem.readInt(u32, hdr[12..16], self.endian);

        self.cursor += 16;
        if (self.bytes.len - self.cursor < incl_len) return error.UnexpectedEof;

        const data = self.bytes[self.cursor .. self.cursor + incl_len];
        self.cursor += incl_len;

        return PcapPacket{
            .sec = sec,
            .usec = usec,
            .orig_len = orig_len,
            .data = data,
        };
    }
};

/// Parsed Android HCI Btsnoop packet record.
pub const BtsnoopPacket = struct {
    is_received: bool,
    orig_len: u32,
    timestamp_us: u64,
    data: []const u8,
};

/// Zero-allocation streaming reader for Android `btsnoop_hci.log` files (RFC 1761).
pub const BtsnoopReader = struct {
    bytes: []const u8,
    cursor: usize = 0,
    datalink_type: u32 = 0,

    const BTSNOOP_MAGIC = "btsnoop\x00";

    pub fn init(bytes: []const u8) !BtsnoopReader {
        if (bytes.len < 16) return error.PayloadTooShort;
        if (!std.mem.eql(u8, bytes[0..8], BTSNOOP_MAGIC)) return error.InvalidBtsnoopMagic;

        const version = std.mem.readInt(u32, bytes[8..12], .big);
        if (version != 1) return error.UnsupportedBtsnoopVersion;

        const datalink = std.mem.readInt(u32, bytes[12..16], .big);

        return .{
            .bytes = bytes,
            .cursor = 16,
            .datalink_type = datalink,
        };
    }

    /// Reads next btsnoop packet record. Returns `null` at EOF.
    pub fn next(self: *BtsnoopReader) !?BtsnoopPacket {
        if (self.cursor >= self.bytes.len) return null;
        if (self.bytes.len - self.cursor < 24) return error.UnexpectedEof;

        const hdr = self.bytes[self.cursor .. self.cursor + 24];
        const orig_len = std.mem.readInt(u32, hdr[0..4], .big);
        const incl_len = std.mem.readInt(u32, hdr[4..8], .big);
        const flags = std.mem.readInt(u32, hdr[8..12], .big);
        // drops = hdr[12..16]
        const ts = std.mem.readInt(u64, hdr[16..24], .big);

        self.cursor += 24;
        if (self.bytes.len - self.cursor < incl_len) return error.UnexpectedEof;

        const data = self.bytes[self.cursor .. self.cursor + incl_len];
        self.cursor += incl_len;

        return BtsnoopPacket{
            .is_received = (flags & 0x01) != 0,
            .orig_len = orig_len,
            .timestamp_us = ts,
            .data = data,
        };
    }
};

test "PcapReader roundtrip verification against PcapWriter" {
    var buffer: [512]u8 = undefined;
    var writer = BufferWriter.init(&buffer);

    var pcap = PcapWriter(*BufferWriter).init(&writer);
    try pcap.writeHeader();

    const sample1 = [_]u8{ 0x01, 0x02, 0x03 };
    const sample2 = [_]u8{ 0xAA, 0xBB, 0xCC, 0xDD };

    try pcap.writePacketWithTimestamp(.command, &sample1, 1000, 2000);
    try pcap.writePacketWithTimestamp(.acl_data, &sample2, 1001, 3000);

    var reader = try PcapReader.init(writer.getWritten());
    try std.testing.expectEqual(LINKTYPE_BLUETOOTH_HCI_H4, reader.link_type);

    const pkt1 = (try reader.next()).?;
    try std.testing.expectEqual(@as(u32, 1000), pkt1.sec);
    try std.testing.expectEqual(@as(u32, 2000), pkt1.usec);
    try std.testing.expectEqual(@as(u8, 0x01), pkt1.data[0]); // H4 command indicator
    try std.testing.expectEqualSlices(u8, &sample1, pkt1.data[1..]);

    const pkt2 = (try reader.next()).?;
    try std.testing.expectEqual(@as(u32, 1001), pkt2.sec);
    try std.testing.expectEqual(@as(u32, 3000), pkt2.usec);
    try std.testing.expectEqual(@as(u8, 0x02), pkt2.data[0]); // H4 acl indicator
    try std.testing.expectEqualSlices(u8, &sample2, pkt2.data[1..]);

    try std.testing.expectEqual(@as(?PcapPacket, null), try reader.next());
}

test "BtsnoopReader decoding test" {
    var fake_btsnoop: [64]u8 = undefined;
    @memcpy(fake_btsnoop[0..8], "btsnoop\x00");
    std.mem.writeInt(u32, fake_btsnoop[8..12], 1, .big); // version 1
    std.mem.writeInt(u32, fake_btsnoop[12..16], 1002, .big); // datalink: HCI UART

    // Packet record: 24 bytes header + 4 bytes payload = 28 bytes
    const p_offset = 16;
    std.mem.writeInt(u32, fake_btsnoop[p_offset .. p_offset + 4], 4, .big); // orig len
    std.mem.writeInt(u32, fake_btsnoop[p_offset + 4 .. p_offset + 8], 4, .big); // incl len
    std.mem.writeInt(u32, fake_btsnoop[p_offset + 8 .. p_offset + 12], 1, .big); // flags: received (bit 0 = 1)
    std.mem.writeInt(u32, fake_btsnoop[p_offset + 12 .. p_offset + 16], 0, .big); // drops
    std.mem.writeInt(u64, fake_btsnoop[p_offset + 16 .. p_offset + 24], 12345678, .big); // ts
    @memcpy(fake_btsnoop[p_offset + 24 .. p_offset + 28], &[_]u8{ 0x04, 0x3E, 0x01, 0x00 }); // LE Meta Event

    var reader = try BtsnoopReader.init(fake_btsnoop[0 .. p_offset + 28]);
    try std.testing.expectEqual(@as(u32, 1002), reader.datalink_type);

    const pkt = (try reader.next()).?;
    try std.testing.expect(pkt.is_received);
    try std.testing.expectEqual(@as(u64, 12345678), pkt.timestamp_us);
    try std.testing.expectEqualSlices(u8, &[_]u8{ 0x04, 0x3E, 0x01, 0x00 }, pkt.data);

    try std.testing.expectEqual(@as(?BtsnoopPacket, null), try reader.next());
}
